name: std-mocks-ci

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [6, 8, 10, 12, 14, 16, 18, 20]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup node.js v${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        
    - name: Verify node.js version
      run: node --version
    - name: Verify npm Version
      run: npm --version     
        
    - name: Install npm dependencies
      run: npm i

    - name: Run test (${{ matrix.os }})
      run: npm run test