name: std-mocks-ci

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12, 14, 16, 18, 20]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm ci
        if: matrix.node >= 16

      - name: Install npm dependencies
        run: npm i
        if: matrix.node < 16

      - name: Run test (${{ matrix.os }})
        run: npm test
